spring.application.name=chat-service


spring.datasource.url: jdbc:postgresql://localhost:5432/iconnect_chat_db
spring.datasource.username: postgres
spring.datasource.password: Password


# src/main/resources/application.yml
matrix.admin.token: syt_YWRtaW4_UWaQsxdhfNcSDrTCaIKJ_0sH5MJ
matrix.cleint.token: syt_Y2hhdC1zZXJ2aWNl_HjTVlAdCSWeIrpZSVAxn_2XfGIQ
